HOURLY_DESCRIPTIONS = {
    0: "The moon hangs high in the midnight sky.",
    1: "A deep stillness settles over the world in the witching hour.",
    2: "The stars shine brightly in the pitch-black sky.",
    3: "A faint chill permeates the air before dawn.",
    4: "The horizon begins to pale with the promise of day.",
    5: "The birds begin to stir as the sky turns grey.",
    6: "The first light of dawn breaks over the horizon.",
    7: "The morning sun casts long shadows across the land.",
    8: "The world is fully awake and bustling with morning energy.",
    9: "The sun climbs higher, warming the earth.",
    10: "The day is bright and the sky is a clear azure.",
    11: "The sun approaches its zenith, casting short shadows.",
    12: "The sun hangs directly overhead in the noon sky.",
    13: "The afternoon sun beats down with intensity.",
    14: "The heat of the day persists in the early afternoon.",
    15: "The sun begins its slow descent towards the west.",
    16: "Golden hour approaches as the light softens.",
    17: "Long shadows return as evening draws near.",
    18: "The sun touches the horizon, painting the sky in orange and red.",
    19: "Twilight falls, blurring the lines between day and night.",
    20: "The last traces of daylight fade into the west.",
    21: "Darkness claims the sky, and the stars emerge.",
    22: "The night deepens, wrapping the world in shadow.",
    23: "The world is quiet under the starlit canopy."
}
